### PR TITLE
Update babel/cli

### PR DESCRIPTION
**Pull request by icunningham88**
Bumping babel. See output for where the dependency linked:

```
>> npm list glob-parent
├─┬ @babel/cli@7.8.4
│ └─┬ chokidar@2.1.8
│   └── glob-parent@3.1.0
└─┬ eslint@6.8.0
  └── glob-parent@5.1.1
  ```
 
After upgrade:
```
>> npm list glob-parent
├─┬ @babel/cli@7.12.0
│ └─┬ chokidar@3.5.2
│   └── glob-parent@5.1.2
└─┬ eslint@6.8.0
  └── glob-parent@5.1.1

### CODE REVIEW

**Review by brooksRoley — APPROVED** [review]
Minor upgrade 'should' be nonbreaking. 👍 
Maybe the upgrade command/risk assessment in the description to go with the proof of success of original user story. Good job knowing the tools.

**Review by jessewagstaff — APPROVED** [review]
Seems safe as there isn't much (anything?) in this repo that needs to be transpiled by babel.

A larger (out of scope) question: is babel even needed with `json-api-tools` anymore? It is only used on the admin and Zendesk plugin.

**Comment by icunningham88** [comment]
> Minor upgrade 'should' be nonbreaking. 👍
> Maybe the upgrade command/risk assessment in the description to go with the proof of success of original user story. Good job knowing the tools.

@brooksRoley can you elaborate more on this? Is there a certain npm command I can run for this?

**Review by GshafferGrove — APPROVED** [review]

**Comment by icunningham88** [comment]
> Seems safe as there isn't much (anything?) in this repo that needs to be transpiled by babel.
> 
> A larger (out of scope) question: is babel even needed with `json-api-tools` anymore? It is only used on the admin and Zendesk plugin.

I believe it's primarily for jest, so we would still need it?

**Pull request merged**
