### PR TITLE
Upgrade command lock update.

### PR DESCRIPTION
**Pull request by brooksRoley**
Still looking how to check this but to reproduce.
```
git clone {thisRepo}
brew install yarn
yarn upgrade
git add .
git commit -m "Did you mean Recursion?"
```

### CODE REVIEW

**Comment by tochiaigrove** [comment]
weird, is this trying to publish the code to a repo even though it's just a PR? that seems premature
```
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You cannot publish over the previously published versions: 0.0.15. : json-api-tools

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-12-01T01_42_23_058Z-debug.log
```

**Review by stephenmcrowe — APPROVED** [review]
Just from skimming this I only see minor version upgrades, so they should all still work. Nice find!

**Comment by al-the-x** [comment]
> weird, is this trying to publish the code to a repo even though it's just a PR? that seems premature

See #6 for resolution. Now needs rebase on `master` from security upgrades. Sorry not sorry.

**Comment by al-the-x** [comment]
@brooksRoley Can you provide what problem you are solving and what you did to correct? Staring at a `yarn.lock` diff rn... 🤕

**Comment by brooksRoley** [comment]
https://groveco.atlassian.net/browse/DE-944

**Pull request closed without merging**
